version: 2
jobs:
  install:
    working_directory: ~/circleci-workflows
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test:
    working_directory: ~/circleci-workflows
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: test
          command: npm test

  release:
    working_directory: ~/circleci-workflows
    docker:
      - image: circleci/node:8.9.4
    steps:
      - add_ssh_keys:
          fingerprints:
            - "65:c0:54:f1:fd:a4:da:32:d6:79:9b:1f:2e:f3:1d:e7"
      - run:
          name: release-version
          command: |
            PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
            git tag $PACKAGE_VERSION
            git push origin $PACKAGE_VERSION

workflows:
  version: 2
  install-test-and-release:
    jobs:
       - install
       - test:
            requires:
                - install
       - release:
            requires:
                - test
            filters:
                branches:
                    only: master