version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache 
        key: dependency-cache-{{ checksum "package.json" }}
      - run: 
        name: npm-install
        command: 'npm i'
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules