name: Node CI

on: [push]

jobs:
  install-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.9.4]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, and test
      run: |
        npm install
        npm test
      env:
        CI: true
    
  release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.9.4]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: release version
      run: |
        PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
        git tag $PACKAGE_VERSION
        git push origin $PACKAGE_VERSION
      env:
        CI: true
